# Generated by Django 3.2.4 on 2021-06-08 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20210608_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='title2',
        ),
    ]
